# Generated by Django 5.2.4 on 2025-08-09 14:33

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_image_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.project_image_upload_path),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.service_icon_upload_path),
        ),
    ]
