# Generated by Django 5.2.4 on 2025-08-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_image_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Public', 'Public')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Interior', 'Interior'), ('Exterior', 'Exterior'), ('Landscape', 'Landscape'), ('Renovation', 'Renovation')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('Design', 'Design'), ('Planning', 'Planning'), ('Consulting', 'Consulting'), ('Visualization', 'Visualization')], max_length=50, null=True),
        ),
    ]
