# Generated by Django 5.2.4 on 2025-08-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_category_project_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Kitchen', 'Kitchen'), ('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Exterior', 'Exterior'), ('Garden', 'Garden'), ('Renovation', 'Renovation'), ('Office', 'Office'), ('Restaurant', 'Restaurant'), ('Retail', 'Retail'), ('Hotel', 'Hotel'), ('Healthcare', 'Healthcare'), ('Industrial', 'Industrial'), ('Educational', 'Educational'), ('Cultural', 'Cultural'), ('Religious', 'Religious'), ('Transportation', 'Transportation'), ('Recreation', 'Recreation')], max_length=50, null=True),
        ),
    ]
