# Generated by Django 5.2.4 on 2025-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Architectural Design', 'Architectural Design'), ('Interior Design', 'Interior Design'), ('Landscape Design', 'Landscape Design'), ('Urban Planning', 'Urban Planning'), ('Structural Design', 'Structural Design'), ('MEP Design', 'MEP Design'), ('Facade Design', 'Facade Design'), ('Site Planning', 'Site Planning'), ('Master Planning', 'Master Planning'), ('Zoning Analysis', 'Zoning Analysis'), ('Feasibility Study', 'Feasibility Study'), ('Environmental Planning', 'Environmental Planning'), ('Traffic Planning', 'Traffic Planning'), ('Infrastructure Planning', 'Infrastructure Planning'), ('Design Consultation', 'Design Consultation'), ('Project Management', 'Project Management'), ('Construction Administration', 'Construction Administration'), ('Code Compliance', 'Code Compliance'), ('Sustainability Consulting', 'Sustainability Consulting'), ('Cost Estimation', 'Cost Estimation'), ('Risk Assessment', 'Risk Assessment'), ('3D Rendering', '3D Rendering'), ('Animation', 'Animation'), ('Virtual Reality', 'Virtual Reality'), ('Architectural Photography', 'Architectural Photography'), ('Presentation Design', 'Presentation Design'), ('Technical Drawing', 'Technical Drawing'), ('Model Making', 'Model Making')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Public', 'Public'), ('Industrial', 'Industrial'), ('Landscape', 'Landscape'), ('Interior', 'Interior'), ('Urban', 'Urban'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Single Family Home', 'Single Family Home'), ('Multi Family Home', 'Multi Family Home'), ('Apartment Complex', 'Apartment Complex'), ('Townhouse', 'Townhouse'), ('Villa', 'Villa'), ('Penthouse', 'Penthouse'), ('Studio Apartment', 'Studio Apartment'), ('Office Building', 'Office Building'), ('Shopping Mall', 'Shopping Mall'), ('Restaurant', 'Restaurant'), ('Hotel', 'Hotel'), ('Retail Store', 'Retail Store'), ('Warehouse', 'Warehouse'), ('Showroom', 'Showroom'), ('Clinic', 'Clinic'), ('Bank', 'Bank'), ('School', 'School'), ('University', 'University'), ('Hospital', 'Hospital'), ('Museum', 'Museum'), ('Library', 'Library'), ('Government Building', 'Government Building'), ('Community Center', 'Community Center'), ('Religious Building', 'Religious Building'), ('Transportation Hub', 'Transportation Hub'), ('Manufacturing Plant', 'Manufacturing Plant'), ('Power Plant', 'Power Plant'), ('Chemical Plant', 'Chemical Plant'), ('Food Processing', 'Food Processing'), ('Automotive Plant', 'Automotive Plant'), ('Steel Mill', 'Steel Mill'), ('Oil Refinery', 'Oil Refinery'), ('Research Facility', 'Research Facility'), ('Public Garden', 'Public Garden'), ('Private Garden', 'Private Garden'), ('Urban Plaza', 'Urban Plaza'), ('Playground', 'Playground'), ('Sports Complex', 'Sports Complex'), ('Park', 'Park'), ('Golf Course', 'Golf Course'), ('Cemetery', 'Cemetery'), ('Living Room', 'Living Room'), ('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Office Space', 'Office Space'), ('Restaurant Interior', 'Restaurant Interior'), ('Hotel Room', 'Hotel Room'), ('Reception Area', 'Reception Area'), ('Master Planning', 'Master Planning'), ('Mixed Use Development', 'Mixed Use Development'), ('Transit Oriented', 'Transit Oriented'), ('Waterfront Development', 'Waterfront Development'), ('Historic District', 'Historic District'), ('Smart City', 'Smart City'), ('Sustainable Community', 'Sustainable Community'), ('Urban Renewal', 'Urban Renewal'), ('Custom Design', 'Custom Design'), ('Prototype', 'Prototype'), ('Renovation', 'Renovation'), ('Restoration', 'Restoration'), ('Conceptual', 'Conceptual'), ('Competition Entry', 'Competition Entry')], max_length=50, null=True),
        ),
    ]
