# Generated by Django 5.2.4 on 2025-08-09 15:47

from django.db import migrations


def clear_admin_logs(apps, schema_editor):
    """Clear any existing admin logs to prevent foreign key issues"""
    LogEntry = apps.get_model('admin', 'LogEntry')
    LogEntry.objects.all().delete()


def reverse_clear_admin_logs(apps, schema_editor):
    """No reverse operation needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_user_options_alter_user_managers_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.RunPython(clear_admin_logs, reverse_clear_admin_logs),
    ]
