# Generated by Django 5.2.4 on 2025-08-09 15:49

from django.db import migrations, connection


def fix_admin_log_foreign_key(apps, schema_editor):
    """Fix the foreign key constraint in django_admin_log to point to our custom user model"""
    with connection.cursor() as cursor:
        # Drop the old foreign key constraint
        cursor.execute("""
            ALTER TABLE django_admin_log 
            DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_auth_user_id;
        """)
        
        # Add the new foreign key constraint pointing to our custom user table
        cursor.execute("""
            ALTER TABLE django_admin_log 
            ADD CONSTRAINT django_admin_log_user_id_fk_portfolio_user 
            FOREIGN KEY (user_id) REFERENCES portfolio_user(id) ON DELETE CASCADE;
        """)


def reverse_fix_admin_log_foreign_key(apps, schema_editor):
    """Reverse the foreign key fix (for migration rollback)"""
    with connection.cursor() as cursor:
        # Drop the new constraint
        cursor.execute("""
            ALTER TABLE django_admin_log 
            DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fk_portfolio_user;
        """)
        
        # Restore the old constraint (though this might fail if auth_user doesn't exist)
        try:
            cursor.execute("""
                ALTER TABLE django_admin_log 
                ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id 
                FOREIGN KEY (user_id) REFERENCES auth_user(id) ON DELETE CASCADE;
            """)
        except:
            pass  # Ignore if auth_user table doesn't exist


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20250809_1847'),
    ]

    operations = [
        migrations.RunPython(fix_admin_log_foreign_key, reverse_fix_admin_log_foreign_key),
    ]
