# Generated by Django 5.2.4 on 2025-08-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projectcategory_servicecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dynamic_category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dynamic_subcategory',
        ),
        migrations.RemoveField(
            model_name='service',
            name='dynamic_category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='dynamic_subcategory',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select the main category for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectcategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Select a subcategory (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectsubcategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select the main category for this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='portfolio.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Select a subcategory (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='portfolio.servicesubcategory'),
        ),
    ]
