# Generated by Django 5.2.4 on 2025-08-16 14:37

import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.project_image_upload_path, validators=[portfolio.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.service_icon_upload_path, validators=[portfolio.models.validate_image]),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Album image file', upload_to=portfolio.models.project_album_image_upload_path, validators=[portfolio.models.validate_image])),
                ('title', models.CharField(blank=True, help_text='Optional title/caption for this image', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for this image', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images should be displayed (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='album_images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Album image file', upload_to=portfolio.models.service_album_image_upload_path, validators=[portfolio.models.validate_image])),
                ('title', models.CharField(blank=True, help_text='Optional title/caption for this image', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for this image', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images should be displayed (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(help_text='Service this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='album_images', to='portfolio.service')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
