# Generated by Django 5.2.4 on 2025-08-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_project_image_alter_service_icon_projectimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this image (leave empty for bulk uploads)', null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title/caption for this image (leave empty for bulk uploads)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this image (leave empty for bulk uploads)', null=True),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title/caption for this image (leave empty for bulk uploads)', max_length=200, null=True),
        ),
    ]
