# Generated by Django 5.2.4 on 2025-08-19 02:43

import django.utils.timezone
from django.db import migrations, models


def set_project_date_from_created_at(apps, schema_editor):
    """Set project_date to the date part of created_at for existing projects"""
    Project = apps.get_model('portfolio', 'Project')
    for project in Project.objects.all():
        project.project_date = project.created_at.date()
        project.save()


def reverse_set_project_date(apps, schema_editor):
    """Reverse operation - nothing needed since we're removing the field"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_projectimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date when this project was completed or published', verbose_name='Project Date'),
            preserve_default=False,
        ),
        migrations.RunPython(set_project_date_from_created_at, reverse_set_project_date),
    ]
