# Generated by Django 5.2.4 on 2025-08-19 02:52

import django.utils.timezone
from django.db import migrations, models


def set_service_date_to_today(apps, schema_editor):
    """Set service_date to today for existing services"""
    from django.utils import timezone
    Service = apps.get_model('portfolio', 'Service')
    today = timezone.now().date()
    for service in Service.objects.all():
        service.service_date = today
        service.save()


def reverse_set_service_date(apps, schema_editor):
    """Reverse operation - nothing needed since we're removing the field"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_add_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date when this service was launched or should be displayed as', verbose_name='Service Date'),
            preserve_default=False,
        ),
        migrations.RunPython(set_service_date_to_today, reverse_set_service_date),
    ]
