# Generated by Django 5.2.4 on 2025-08-19 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_add_service_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order'], 'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['order'], 'verbose_name': 'Service Image', 'verbose_name_plural': 'Service Images'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='created_at',
        ),
    ]
