# Generated by Django 5.2.4 on 2025-08-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_created_at_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_date',
        ),
    ]
