# Generated by Django 5.2.4 on 2025-08-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_convert_to_many_to_many_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-project_date']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order position for manual arrangement. Lower numbers appear first. If 0, projects are ordered by project_date (newest first).'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order position for manual arrangement. Lower numbers appear first. If 0, services are ordered by name.'),
        ),
    ]
