# Generated by Django 5.2.4 on 2025-08-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_add_order_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order position for manual arrangement. Lower numbers appear first. Projects are ordered by this field first, then by project_date (newest first).'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order position for manual arrangement. Lower numbers appear first. Services are ordered by this field first, then by name.'),
        ),
    ]
