# Generated by Django 5.2.4 on 2025-08-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_update_order_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename when uploaded', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename when uploaded', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename when uploaded', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename when uploaded', max_length=255, null=True),
        ),
    ]
