# Generated by Django 5.2.4 on 2025-08-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_add_performance_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='optimized_image',
            field=models.CharField(blank=True, help_text='Path to the optimized .webp version of the main image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='optimized_image_large',
            field=models.CharField(blank=True, help_text='Path to the large optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='optimized_image_medium',
            field=models.CharField(blank=True, help_text='Path to the medium optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='optimized_image_small',
            field=models.CharField(blank=True, help_text='Path to the small optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='optimized_image',
            field=models.CharField(blank=True, help_text='Path to the optimized .webp version of the album image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='optimized_image_large',
            field=models.CharField(blank=True, help_text='Path to the large optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='optimized_image_medium',
            field=models.CharField(blank=True, help_text='Path to the medium optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='optimized_image_small',
            field=models.CharField(blank=True, help_text='Path to the small optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='optimized_icon',
            field=models.CharField(blank=True, help_text='Path to the optimized .webp version of the icon', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='optimized_icon_large',
            field=models.CharField(blank=True, help_text='Path to the large optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='optimized_icon_medium',
            field=models.CharField(blank=True, help_text='Path to the medium optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='optimized_icon_small',
            field=models.CharField(blank=True, help_text='Path to the small optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='optimized_image',
            field=models.CharField(blank=True, help_text='Path to the optimized .webp version of the album image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='optimized_image_large',
            field=models.CharField(blank=True, help_text='Path to the large optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='optimized_image_medium',
            field=models.CharField(blank=True, help_text='Path to the medium optimized .webp version', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='optimized_image_small',
            field=models.CharField(blank=True, help_text='Path to the small optimized .webp version', max_length=500, null=True),
        ),
    ]
