# Generated by Django 5.2.4 on 2025-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_project_optimized_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text="Client's full name", max_length=200)),
                ('client_email', models.EmailField(help_text="Client's email address", max_length=254)),
                ('client_phone', models.CharField(blank=True, help_text="Client's phone number (optional)", max_length=20, null=True)),
                ('booking_date', models.DateField(help_text='Date of the consultation')),
                ('booking_time', models.TimeField(help_text='Start time of the consultation')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of this specific booking in minutes (from settings)')),
                ('message', models.TextField(blank=True, help_text="Client's message about the project or consultation needs", null=True)),
                ('project_type', models.CharField(blank=True, help_text='Type of project the client wants to discuss', max_length=100, null=True)),
                ('budget_range', models.CharField(blank=True, help_text="Client's budget range for the project", max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use only', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultation Booking',
                'verbose_name_plural': 'Consultation Bookings',
                'ordering': ['booking_date', 'booking_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_duration_minutes', models.PositiveIntegerField(default=45, help_text='Duration of each consultation meeting in minutes')),
                ('buffer_time_minutes', models.PositiveIntegerField(default=15, help_text='Buffer time between meetings in minutes')),
                ('monday_start', models.TimeField(blank=True, help_text='Start time on Monday (24-hour format)', null=True)),
                ('monday_end', models.TimeField(blank=True, help_text='End time on Monday (24-hour format)', null=True)),
                ('monday_enabled', models.BooleanField(default=True, help_text='Enable consultations on Monday')),
                ('tuesday_start', models.TimeField(blank=True, help_text='Start time on Tuesday (24-hour format)', null=True)),
                ('tuesday_end', models.TimeField(blank=True, help_text='End time on Tuesday (24-hour format)', null=True)),
                ('tuesday_enabled', models.BooleanField(default=True, help_text='Enable consultations on Tuesday')),
                ('wednesday_start', models.TimeField(blank=True, help_text='Start time on Wednesday (24-hour format)', null=True)),
                ('wednesday_end', models.TimeField(blank=True, help_text='End time on Wednesday (24-hour format)', null=True)),
                ('wednesday_enabled', models.BooleanField(default=True, help_text='Enable consultations on Wednesday')),
                ('thursday_start', models.TimeField(blank=True, help_text='Start time on Thursday (24-hour format)', null=True)),
                ('thursday_end', models.TimeField(blank=True, help_text='End time on Thursday (24-hour format)', null=True)),
                ('thursday_enabled', models.BooleanField(default=True, help_text='Enable consultations on Thursday')),
                ('friday_start', models.TimeField(blank=True, help_text='Start time on Friday (24-hour format)', null=True)),
                ('friday_end', models.TimeField(blank=True, help_text='End time on Friday (24-hour format)', null=True)),
                ('friday_enabled', models.BooleanField(default=True, help_text='Enable consultations on Friday')),
                ('saturday_start', models.TimeField(blank=True, help_text='Start time on Saturday (24-hour format)', null=True)),
                ('saturday_end', models.TimeField(blank=True, help_text='End time on Saturday (24-hour format)', null=True)),
                ('saturday_enabled', models.BooleanField(default=False, help_text='Enable consultations on Saturday')),
                ('sunday_start', models.TimeField(blank=True, help_text='Start time on Sunday (24-hour format)', null=True)),
                ('sunday_end', models.TimeField(blank=True, help_text='End time on Sunday (24-hour format)', null=True)),
                ('sunday_enabled', models.BooleanField(default=False, help_text='Enable consultations on Sunday')),
                ('advance_booking_days', models.PositiveIntegerField(default=30, help_text='How many days in advance can clients book consultations')),
                ('minimum_notice_hours', models.PositiveIntegerField(default=24, help_text='Minimum notice required for booking (in hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultation Settings',
                'verbose_name_plural': 'Consultation Settings',
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when consultations are not available', unique=True)),
                ('reason', models.CharField(blank=True, help_text="Optional reason for the day off (e.g., 'Holiday', 'Vacation')", max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Day Off',
                'verbose_name_plural': 'Days Off',
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['order', '-project_date'], name='portfolio_p_order_0fd969_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_date'], name='portfolio_p_project_389920_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['order'], name='portfolio_p_order_2e0f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'booking_time'], name='portfolio_b_booking_ea56b5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='portfolio_b_status_fa9551_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client_email'], name='portfolio_b_client__b82284_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'booking_time')},
        ),
    ]
