# Generated by Django 5.2.4 on 2025-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_booking_consultationsettings_dayoff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Consultation Booking', 'verbose_name_plural': 'Consultation Bookings'},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='portfolio_b_booking_ea56b5_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'time')},
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='friday_enabled',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='monday_enabled',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='saturday_enabled',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='sunday_enabled',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='thursday_enabled',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='tuesday_enabled',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='wednesday_enabled',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='consultationsettings',
            name='wednesday_start',
        ),
        migrations.AddField(
            model_name='booking',
            name='project_details',
            field=models.TextField(blank=True, help_text="Details about the client's project or consultation needs", null=True),
        ),
        migrations.AddField(
            model_name='consultationsettings',
            name='booking_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable consultation bookings globally'),
        ),
        migrations.AddField(
            model_name='consultationsettings',
            name='friday_hours',
            field=models.CharField(blank=True, help_text="Working hours for Friday (e.g., '09:00-17:00') or leave empty for day off", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultationsettings',
            name='monday_hours',
            field=models.CharField(blank=True, help_text="Working hours for Monday (e.g., '09:00-17:00') or leave empty for day off", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultationsettings',
            name='saturday_hours',
            field=models.CharField(blank=True, help_text="Working hours for Saturday (e.g., '09:00-17:00') or leave empty for day off", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultationsettings',
            name='sunday_hours',
            field=models.CharField(blank=True, help_text="Working hours for Sunday (e.g., '09:00-17:00') or leave empty for day off", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultationsettings',
            name='thursday_hours',
            field=models.CharField(blank=True, help_text="Working hours for Thursday (e.g., '09:00-17:00') or leave empty for day off", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultationsettings',
            name='tuesday_hours',
            field=models.CharField(blank=True, help_text="Working hours for Tuesday (e.g., '09:00-17:00') or leave empty for day off", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultationsettings',
            name='wednesday_hours',
            field=models.CharField(blank=True, help_text="Working hours for Wednesday (e.g., '09:00-17:00') or leave empty for day off", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin use', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(help_text='Email address of the client', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.CharField(help_text='Full name of the client', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, help_text='Phone number of the client (optional)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration of the consultation in minutes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, help_text='Additional message from the client', null=True),
        ),
        migrations.AlterField(
            model_name='consultationsettings',
            name='advance_booking_days',
            field=models.PositiveIntegerField(default=30, help_text='How many days in advance clients can book consultations'),
        ),
        migrations.AlterField(
            model_name='consultationsettings',
            name='minimum_notice_hours',
            field=models.PositiveIntegerField(default=24, help_text='Minimum hours notice required for booking a consultation'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='date',
            field=models.DateField(help_text='Date to block for consultations', unique=True),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='reason',
            field=models.CharField(blank=True, help_text="Optional reason for the day off (e.g., 'Holiday', 'Personal')", max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'time'], name='portfolio_b_date_b1e3aa_idx'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='project_type',
        ),
    ]
