# Generated by Django 5.2.4 on 2025-09-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_add_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='original_file_path',
            field=models.CharField(blank=True, help_text='Path to the original unoptimized file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='original_file_path',
            field=models.CharField(blank=True, help_text='Path to the original unoptimized file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='original_file_path',
            field=models.CharField(blank=True, help_text='Path to the original unoptimized file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='original_file_path',
            field=models.CharField(blank=True, help_text='Path to the original unoptimized file', max_length=500, null=True),
        ),
    ]
